apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulumi-mcp
  namespace: my-reforge-ai
  labels:
    app: pulumi-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulumi-mcp
  template:
    metadata:
      labels:
        app: pulumi-mcp
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: false
        #runAsUser: 1000 # Example user ID, adjust if needed
        #fsGroup: 1000 # Example group ID, adjust if needed
      containers:
        - name: pulumi-mcp-server
          image: ghcr.io/spigell/pulumi-talos-cluster-workbench:3.200.0-54d6cd
          # command: ['/bin/bash', '-c', 'sleep infinity']
          # command: ['/bin/bash', '-lc', 'pulumi-mcp-server http']
          command: ['pulumi-mcp-server', 'http']
          imagePullPolicy: IfNotPresent
          env:
            - name: PULUMI_ACCESS_TOKEN
              value: fake
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 3Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Service
metadata:
  name: pulumi-mcp
  namespace: my-reforge-ai
  labels:
    app: pulumi-mcp
spec:
  selector:
    app: pulumi-mcp
  ports:
    - name: http
      port: 3000
      targetPort: http
